# iOS CircleCI 2.0 configuration file
#

version: 2
jobs:
  build:

    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      - run:
          name: Build Soup
          command: xcodebuild -scheme "Soup"

      - run:
          name: Build addresses
          command: xcodebuild -scheme "addresses" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
